"""Verify the pipeline handles synthetic edge cases described in
`docs/edge-cases.md` and generated by `tests/fixtures/synthetic/gen_synthetic.py`.

Each test loads a single edge-case fixture, runs the relevant pipeline stage,
and asserts the *intended* behavior — what we want a regression check to
catch if the rules / categorizer / sentiment math drift.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

from src import categorizer, data_loader, sentiment

FIXTURES_ROOT = Path(__file__).parent / "fixtures" / "synthetic"


def _load_one(category: str, slug: str) -> pd.DataFrame:
    """Load a single synthetic fixture directory through the real loader."""
    fixture_dir = FIXTURES_ROOT / category / slug
    assert fixture_dir.exists(), f"missing fixture: {fixture_dir}"
    meeting = data_loader.load_meeting(fixture_dir)
    df = data_loader.meetings_to_dataframe([meeting])
    return categorizer.annotate(df)


# ---------------------------------------------------------------------------
# Title-format heterogeneity (case 1)
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("slug,expected_call_type,expected_purpose", [
    # Lowercase URGENT — case-insensitive regex catches it
    ("urgent_lowercase",        "external", "Incident Response"),
    # Compound prefix — fixed by widening the regex from `^urgent:` to
    # `^(urgent|escalation)\b.*?:` (this synthetic fixture caught the gap)
    ("multi_word_escalation",   "external", "Incident Response"),
    # Multi-segment Aegis path — separator-spaces fix lets this still match
    ("nested_aegis",            "external", "Renewal/Contract"),
    # Aegis without "/" separator — correctly falls back to internal
    ("aegis_no_separator",      "internal", "Planning/Strategy"),
    # Em-dash separator + "Post-Incident Review" — "Incident" word triggers
    # Incident Response *before* the Review rule. This is the correct order:
    # an "incident review" meeting is fundamentally about an incident.
    ("trailing_punctuation",    "external", "Incident Response"),
])
def test_title_variant_categorization(slug, expected_call_type, expected_purpose):
    df = _load_one("title_variants", slug)
    row = df.iloc[0]
    assert row["call_type"] == expected_call_type, \
        f"{slug}: got call_type={row['call_type']!r}"
    assert row["meeting_purpose"] == expected_purpose, \
        f"{slug}: got meeting_purpose={row['meeting_purpose']!r}"


# ---------------------------------------------------------------------------
# Customer unicode (case 2)
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("slug,expected_customer", [
    ("apostrophe",  "L'Oreal"),
    ("umlaut",      "Müller GmbH"),
    ("hyphenated",  "Foo-Bar Industries"),
])
def test_customer_unicode_extraction(slug, expected_customer):
    df = _load_one("customer_unicode", slug)
    assert df.iloc[0]["customer"] == expected_customer, \
        f"unicode customer name lost: {df.iloc[0]['customer']!r}"


# ---------------------------------------------------------------------------
# Net-new product (case 3)
# ---------------------------------------------------------------------------
def test_net_new_product_detect_plus_falls_back_gracefully():
    """DetectPlus contains 'detect' so the keyword match SHOULD fire — verifying
    that current behavior. (Documents the intended semantics; if DetectPlus is
    later treated as a separate product, update keyword config + this test.)"""
    df = _load_one("net_new_product", "detect_plus_preview")
    assert "Detect" in df.iloc[0]["product_areas"]


def test_net_new_product_comply_vault_falls_back_gracefully():
    """ComplyVault contains 'comply' — same reasoning as DetectPlus."""
    df = _load_one("net_new_product", "comply_vault_intro")
    assert "Comply" in df.iloc[0]["product_areas"]


def test_truly_unknown_product_lands_in_general():
    """Sanity check: a meeting referencing no known product keyword lands in
    the 'General' fallback bucket rather than silently disappearing."""
    df = _load_one("internal_mentions_customer", "account_strategy_internal")
    # The strategy meeting mentions Northstar Pharma + SentinelShield (a
    # competitor); neither matches our product-area keywords.
    assert df.iloc[0]["product_areas"] == ["General"]


# ---------------------------------------------------------------------------
# All-neutral long meeting (case 4) — verify trajectory math doesn't fire
# false friction signals
# ---------------------------------------------------------------------------
def test_all_neutral_meeting_has_zero_max_drop():
    df = _load_one("all_neutral", "weekly_status")
    sentences = data_loader.sentences_dataframe([
        data_loader.load_meeting(FIXTURES_ROOT / "all_neutral" / "weekly_status")
    ])
    df = sentiment.add_trajectories(df, sentences)
    row = df.iloc[0]
    # All neutral → trajectory all zeros → max_drop should be 0
    assert row["max_drop"] == 0.0, \
        f"flat meeting flagged a friction moment: max_drop={row['max_drop']}"
    assert row["share_negative"] == 0.0


# ---------------------------------------------------------------------------
# Single-sentence meeting (case 5) — verify bucket math doesn't crash
# ---------------------------------------------------------------------------
def test_single_sentence_does_not_crash():
    """Pipeline must not blow up on a meeting with N < n_buckets sentences."""
    df = _load_one("single_sentence", "quick_sync")
    sentences = data_loader.sentences_dataframe([
        data_loader.load_meeting(FIXTURES_ROOT / "single_sentence" / "quick_sync")
    ])
    df = sentiment.add_trajectories(df, sentences)
    row = df.iloc[0]
    # Trajectory should still be 5 buckets long
    assert isinstance(row["trajectory"], list)
    assert len(row["trajectory"]) == 5
    # No NaN poisoning of downstream signals
    assert not pd.isna(row["max_drop"])


# ---------------------------------------------------------------------------
# Multi-incident scenario (case 6)
# ---------------------------------------------------------------------------
def test_multi_incident_categorized_as_incident_response():
    df = _load_one("multi_incident", "dual_outage_review")
    row = df.iloc[0]
    assert row["meeting_purpose"] == "Incident Response"
    # Both Detect and Comply should be detected
    assert "Detect" in row["product_areas"]
    assert "Comply" in row["product_areas"]


# ---------------------------------------------------------------------------
# Historical incident reference (case 7)
# ---------------------------------------------------------------------------
def test_historical_incident_does_not_dominate_classification():
    """A meeting that *mentions* an old outage should not be classified as
    Incident Response — the title is a Q2 business review, not an active
    incident. Catches a subtle rule-bleed regression."""
    df = _load_one("historical_incident", "postmortem_review")
    row = df.iloc[0]
    assert row["meeting_purpose"] != "Incident Response", \
        "historical mention shouldn't classify as active incident response"


# ---------------------------------------------------------------------------
# Internal-meeting + customer name mention (case 8)
# ---------------------------------------------------------------------------
def test_internal_strategy_classifies_as_internal_not_external():
    """Customer name in the title doesn't make it an external meeting if
    the prefix isn't 'Aegis /' or 'URGENT:'."""
    df = _load_one("internal_mentions_customer", "account_strategy_internal")
    row = df.iloc[0]
    assert row["call_type"] == "internal", \
        f"internal strategy mis-classified as {row['call_type']!r}"
    assert row["customer"] is None, \
        f"customer extracted from internal meeting title: {row['customer']!r}"


# ---------------------------------------------------------------------------
# End-to-end smoke: load ALL synthetic fixtures, run the full pipeline
# ---------------------------------------------------------------------------
def test_all_synthetic_fixtures_load_and_categorize():
    """Bulk smoke test — every fixture loads, categorizes, and produces a
    valid trajectory. Catches accidental regressions that affect a class of
    inputs we didn't write a specific test for."""
    meeting_dirs = list(FIXTURES_ROOT.rglob("meeting-info.json"))
    assert len(meeting_dirs) >= 8, "expected at least 8 synthetic fixtures"

    meetings = [data_loader.load_meeting(p.parent) for p in meeting_dirs]
    df = data_loader.meetings_to_dataframe(meetings)
    df = categorizer.annotate(df)
    sentences = data_loader.sentences_dataframe(meetings)
    df = sentiment.add_trajectories(df, sentences)

    # Every row gets a categorization
    assert df["call_type"].isin(["support", "external", "internal"]).all()
    assert df["meeting_purpose"].notna().all()
    assert df["product_areas"].apply(lambda x: len(x) > 0).all()
    # Every row gets a 5-bucket trajectory
    assert df["trajectory"].apply(lambda t: isinstance(t, list) and len(t) == 5).all()
